# Can override the default connection name with an environment variable as follows
export SNOWFLAKE_DEFAULT_CONNECTION_NAME="default"

[default]
account = "jcfhviz-kpb03549"
user = "joeparker0412"
password = "363H@lsey"
role = "HOL_ROLE"
warehouse = "HOL_WH"
database = "HOL_DB"
schema = "ANALYTICS"
